# fly.toml app configuration file generated for sivukhin-turso-benchmark on 2025-10-19T16:45:18+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sivukhin-turso-benchmark'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
